Cliente/urls.py
app_name = 'servicios'

from django.urls import path
from .views import CodigoForm

urlpatterns = [
    path('',CodigoForm.as_view(),name='formCodigo'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Cliente.urls',namespace="servicios"))
]

Cliente/models.py
from django.db import models
import django.utils.timezone 

# Create your models here.

EstadoOpciones  = (
 ('En Arreglo','En Arreglo'),
 ('Listo para retirar','Listo para retirar'),
 ('Aceptado','Aceptado'),
 ('No se puede arreglar','No se puede arreglar'),
 ('ENTREGADO','ENTREGADO')
)

reparacionOpciones  = (
 ('Reparacion por garantia','Reparacion por garantia'),
 ('reparacion por cuenta del cliente','reparacion por cuenta del cliente'),

)


class Tecnico(models.Model):
    nombre_apellido = models.CharField("Nombre del tecnico", max_length=500)
    
    def __str__(self):  # Método para personalizar la representación en cadena
        return self.nombre_apellido

class Servicio(models.Model):
    id = models.AutoField(primary_key=True, unique=True)

    # ORDEN DE RECEPCION
    codigo = models.CharField("codigo de seguimiento", default= "", max_length=100, blank=True, null=True)
    fecha_deja_prod = models.DateTimeField("Fecha entrada", default=django.utils.timezone.now, editable=True, blank=False)
    nombre_apellido = models.CharField("Nombre y Apellido", max_length=126, default="", blank=False, null=True)
    telefono_contacto = models.CharField(("Telefono de contacto"), default="+549", max_length=40, blank=True, null=True)
    equipo = models.CharField("Equipo", max_length=126, default="", blank=True, null=True)
    modelo_equipo = models.CharField("Modelo del equipo", max_length=126, default="", blank=True, null=True)
    imei = models.IntegerField("Imei del equipo", default=0, blank=True, null=True)
    descripcion_problema = models.TextField(("Breve descripcion del problema"), max_length=512, default="", blank=True, null=True)
    mensaje = models.TextField("Mensaje que se enviara", max_length=500, null= True)
    # TIPO DE REPARACION
    tipo_reparacion = models.CharField("tipo de reparacion", choices=reparacionOpciones, default="reparacion por cuenta del cliente", max_length=200, blank=False)    

    # DETALLES DEL PRODUCTO
    fisuras = models.BooleanField("Fisuras/Quebraduras",default=False )
    pintura = models.BooleanField("Pintura dañada",default=False )
    marcas = models.BooleanField("Marcas/Rayones",default=False )
    golpes_graves = models.BooleanField("Golpes Graves",default=False )
    manchas = models.BooleanField("Manchas",default=False )
    golpes_leves= models.BooleanField("Golpes leves",default=False )    
    otros = models.CharField("Otros", max_length=150, default = "", blank=True, null=True)

    #MAS DATOS SIN SECCION ESPECIFICA
    objectos = models.TextField(("Objectos que deja"), max_length=512, default="", blank=True, null=True)
    fecha_terminacion_prod = models.DateTimeField("Fecha Salida", editable=True, blank=False)
    monto_total = models.IntegerField("Monto total (Aprox)", default=0, blank=True, null=True)

    tecnico = models.ForeignKey(Tecnico, on_delete=models.SET_NULL, blank=True, null=True)
    parte_pago = models.IntegerField("Pago por adelantado", default=0, blank=True, null=True)

    estado = models.CharField("Estado del pedido", choices=EstadoOpciones, default="Aceptado" , max_length=20, blank=True, null=True)
    dibujo_patron = models.IntegerField("Patron",default=0, blank=True)
    codigo_patron = models.CharField("Contrasena/Pin", default="",blank=True, max_length=100)




    def get_data(self):
        return {
            "estado":self.estado,
            "montoTotal":self.monto_total,            
            "partePago":self.parte_pago,
            "finalizacion":self.fecha_terminacion_prod,
            "nombre":self.nombre_apellido,
            "problema":self.descripcion_problema,
            "aPagar":self.monto_total - self.parte_pago,
            "codigo":self.codigo,
            "equipo":self.equipo,
            "modelo":self.modelo_equipo
        }
    def __str__(self):
        return f"El usuario {self.nombre_apellido}"

Cliente/forms.py
from django import forms
from .models import Servicio


class FormServicio(forms.ModelForm):    
    class Meta:
        model = Servicio
        exclude = ['codigo','estado']

class FormCodigo(forms.ModelForm):    
    class Meta:
        model = Servicio
        fields = ['codigo']

Cliente/views.py
from django.shortcuts import render
from django.views import View
from .forms import FormCodigo
from .models import Servicio

class CodigoForm(View):
    def get(self,request,*args, **kwargs):
        contexto = {
            'formulario':FormCodigo()
        }
        return render(request,'home.html',contexto)
    
    def post(self,request,*args, **kwargs):
        form = FormCodigo(request.POST)
        if form.is_valid():
            codigo = form.cleaned_data.get('codigo')
            try:
                servicio = Servicio.objects.get(codigo=codigo)
            except Servicio.DoesNotExist:
                form.add_error('codigo', 'Código no encontrado, por favor vuelve a intentarlo.')
                return render(request, 'home.html', {'formulario': form})
            contexto = {
                "servicio":servicio.get_data()
            }
            return render(request,"pedido.html",contexto)        
        return render(request,'home.html', {'formulario': form})

templates/codigo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'form_codigo.css' %}">
    <title>Bienvenido a Soporte Técnico 9 BITS</title>
    <style>
        ul {
            list-style: none;
        }
    </style>
</head>

<body class="gradient-bg" style="background-color:">

    <div id="elemento"class="container bg-white text-center p-5 rounded my-5 mx-auto" style="max-width: 500px; box-shadow: 0 0 20px #00BFFF;">
        <img src="https://9bits.com.ar/v31/wp-content/uploads/2022/09/cropped-12anos.jpg" alt="Mi Foto" class="rounded-img my-4">
        <h1 class="text-dark">Soporte Técnico</h1>
        <p class="text-dark">¡Hola! Somos 9 Bits, tus técnicos de confianza. Estamos aquí para ayudarte con cualquier problema que puedas tener. Con más de 12 años de experiencia, comprometidos a brindarte soluciones efectivas y un servicio de calidad.</p>

        <h3 class="text-dark my-4">Estado de tu pedido</h3>
        <p>Introduce el código que te proporcionamos previamente para poder monitorear el estado de tu pedido y acceder a otros detalles relevantes.</p>
        <form method="post" class="text-left">
            {% csrf_token %}
            <center>
                <input type="text" name="codigo" value="" required>
                {% if formulario.codigo.errors %}
                    <div class="alert alert-danger mt-2" style="">
                        {{ formulario.codigo.errors }}
                    </div>
                {% endif %}
            </center>
            <br>
            <div class="inputbox text-center">
                <input type="submit" value="Consultar" class="myButton">
            </div>
        </form>
    </div>
</body>

</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <title>Bienvenido a Soporte Técnico 9 BITS</title>
    <style>
        body {
            font-family: 'Oswald';
            margin: 0;
            padding: 0;
        }
        ul {
            list-style: none;
        }
        body {
            font-family: 'Oswald';
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-image: linear-gradient(180deg, #a6ffff 0%, #a2edff 25%, #9dd5f2 50%, #96bed5 75%, #8ea8b9 100%);
        }
        
        .container {
            text-align: center;
            padding: 15px;
            background: white;
            border-radius: 5px;
        }
        
        h1, h2 {
            color: #000000;
        }
        
        p {
            color: #000000;
        }
        
        img {
            width: 250px;
            height: 150px;
        }
        
        .myButton {
            box-shadow:inset 0px -3px 7px 0px #29bbff;
            background:linear-gradient(to bottom, #2dabf9 5%, #0688fa 100%);
            background-color:#2dabf9;
            border-radius:3px;
            border:1px solid #0b0e07;
            display:inline-block;
            cursor:pointer;
            color:#ffffff;
            font-family:Arial;
            font-size:15px;
            padding:9px 23px;
            text-decoration:none;
            text-shadow:0px 1px 0px #263666;
        }
        
        .myButton:hover {
            background:linear-gradient(to bottom, #0688fa 5%, #2dabf9 100%);
            background-color:#0688fa;
        }
        
        .myButton:active {
            position:relative;
            top:1px;
        }
        /* Responsive adjustments */
        @media screen and (max-width: 600px) {
            .container {
                width: 100%;
            }

            img {
                width: 100px;
                height: 100px;
            }

            .myButton {
                font-size: 12px;
                padding: 7px 20px;
            }
        }

        @media screen and (min-width: 601px) and (max-width: 1024px) {
            .container {
                width: 80%;
            }

            img {
                width: 130px;
                height: 130px;
            }

            .myButton {
                font-size: 14px;
                padding: 8px 22px;
            }
        }
    </style>
</head>

<body>

    <div class="gradient-bg d-flex align-items-center justify-content-center">
        <div id="elemento" class="container bg-white text-center p-5 rounded my-5 mx-auto" style="max-width: 500px; box-shadow: 0 0 20px #00BFFF;">
            <img src="https://9bits.com.ar/v31/wp-content/uploads/2022/09/cropped-12anos.jpg" alt="Mi Foto">
            <h1 class="text-dark">Soporte Técnico</h1>
            <p class="text-dark">¡Hola! Somos 9 Bits, tus técnicos de confianza. Estamos aquí para ayudarte con cualquier problema que puedas tener. Con más de 12 años de experiencia, comprometidos a brindarte soluciones efectivas y un servicio de calidad.</p>
            <br>
            <h4 class="text-dark">Tu Servicio</h4>
            <p>Introduce el código que te proporcionamos previamente para poder monitorear el estado de tu servicio y acceder a otros detalles relevantes.</p>
            <form method="post" class="text-left">
                {% csrf_token %}
                <center>
                    <input type="text" name="codigo" value="" required>
                    {% if formulario.codigo.errors %}
                        <div class="alert alert-danger mt-2" style="">
                            {{ formulario.codigo.errors }}
                        </div>
                    {% endif %}
                </center>
                <br>
                <div class="inputbox text-center">
                    <input type="submit" value="Consultar" class="myButton">
                </div>
            </form>
        </div>
    </div>
</body>
</html>

templates/index.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SVG Based Pattern Lock Example</title>
    <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <style media="screen">
        * {
            box-sizing: border-box;
        }

        html,
        body {
            padding: 0;
            margin: 0;
            height: 100vh;
            max-height: 100vh;
            overflow: hidden;
        }

        body {
            font-family: 'Varela Round', sans-serif;
            background-color: #fafafa;
        }

        .container {
            margin: 150px auto;
            height: 100%;
        }

        h1 {
            text-align: center;
            margin: 0;
            height: 15vh;
            line-height: 15vh;
            text-align: center;
            font-size: 6vh;

        }

        #lock {
            width: 100%;
            height: calc(100% - 15vh);
            padding-bottom: 12vh;
            min-height: 120px;
        }

        .stars {
            margin: auto;
            display: block;
        }
    </style>

    <link rel="stylesheet" href="{% static "styles.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
</head>

<body>
<div id="jquery-script-menu">
<div class="jquery-script-center">

<div class="jquery-script-ads"><script type="text/javascript"><!--
google_ad_client = "ca-pub-2783044520727903";
/* jQuery_demo */
google_ad_slot = "2780937993";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="https://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></div>
<div class="jquery-script-clear"></div>
</div>
</div>
    <div class="container">
        <h1>Patron Cliente</h1>
        <svg class="patternlock" id="lock" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <g class="lock-actives"></g>
            <g class="lock-lines"></g>
            <g class="lock-dots">
                <circle cx="20" cy="20" r="2"/>
                <circle cx="50" cy="20" r="2"/>
                <circle cx="80" cy="20" r="2"/>

                <circle cx="20" cy="50" r="2"/>
                <circle cx="50" cy="50" r="2"/>
                <circle cx="80" cy="50" r="2"/>

                <circle cx="20" cy="80" r="2"/>
                <circle cx="50" cy="80" r="2"/>
                <circle cx="80" cy="80" r="2"/>
            </g>
        <svg>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src=" {% static "patternlock.js" %}"></script>

    <script type="text/javascript">
    var e = document.getElementById('lock')
    var p = new PatternLock(e, {
        onPattern: function() {
            this.success()
        }
    });
    </script>
</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</html>

templates/pedido.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <style>
        body {
            font-family: 'Oswald';
            }
            body.gradient-bg {
                font-family: 'Arial', sans-serif;
                background-image: linear-gradient(180deg, #a6ffff 0, #a2edff 25%, #9dd5f2 50%, #96bed5 75%, #8ea8b9 100%);
                margin: 0;
                padding: 0;
                display: flex;
                flex-direction: column;
                align-items: center;
                width: 100%;
                height: 100vh;
            }
            
            .container {
                text-align: center;
                max-width: 800px;
                background-color: white;
                padding: 5rem;
                border-radius: 0.25rem;
                box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
            }
            
            .myButton {
                box-shadow: inset 0px -3px 7px 0px #29bbff;
                background: linear-gradient(to bottom, #2dabf9 5%, #0688fa 100%);
                background-color:#2dabf9;
                border-radius:3px;
                border:1px solid #0b0e07;
                display:inline-block;
                cursor:pointer;
                color:#ffffff;
                font-family:Arial;
                font-size:15px;
                padding:9px 23px;
                text-decoration: none; /* Añade esta línea */
                text-shadow:0px 1px 0px #263666;
            }
            
            .myButton:hover {
                color: aliceblue;
                background: linear-gradient(to bottom, #0688fa 5%, #2dabf9 100%);
                background-color:#0688fa;
                text-decoration: none;
            }
            
            .myButton:active {
                position:relative;
                top:1px;
                text-decoration: none;
            }
        </style>
    <title>Detalle del Pedido</title>

</head>

<body class="gradient-bg">

    <div class="container text-center p-5 my-5 rounded shadow-lg" style="max-width: 800px; background-color: white;">
        <h5>ESTADO DE TU SERVICIO</h5>
        <div class="progress my-4 position-relative" style="height: 30px;">
            <div class="progress-bar progress-bar-striped 
                {% if servicio.estado == 'Aceptado' %} bg-info
                {% elif servicio.estado == 'En Arreglo' %} bg-warning
                {% elif servicio.estado == 'No se puede arreglar' %} bg-danger
                {% else %} bg-success
                {% endif %}" 
                role="progressbar" style="width: {% if servicio.estado == 'Aceptado' %} 20%
                {% elif servicio.estado == 'En Arreglo' %} 60%
                {% elif servicio.estado == 'No se puede arreglar' %} 100%
                {% else %} 100%
                {% endif %};" 
                aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
            </div>
            <span style="position: absolute; width: 100%; left: 0; top: 50%; transform: translate(0, -50%); text-align: center; 
                {% if servicio.estado == 'Aceptado' %} color: blue;
                {% elif servicio.estado == 'En Arreglo' %} color: black;
                {% elif servicio.estado == 'No se puede arreglar' %} color: white;
                {% else %} color: black;
                {% endif %}">
                {{servicio.estado | upper}}
            </span>
        </div>


        <div class="row">
            <div class="col-12 text-left border border-info rounded p-3 my-2 alert alert-info">
                <h5 class="my-3">DETALLES DEL PEDIDO:</h5>
                <div class="detalle-pedido">
                    <p>Fecha estimada de finalización: {{servicio.finalizacion}}</p>
                    <p>Problema del producto: {{servicio.problema}}</p>
                    <p>Nos trajiste un equipo {{servicio.equipo}}{{servicio.modelo}}</p>

                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6 text-left border border-warning  alert alert-warning rounded p-3 my-2">
                <h5 class="my-3">DETALLES DEL PAGO</h5>
                <div class="d-flex justify-content-between">
                    <p>Monto total a pagar:</p>
                    <p>${{servicio.montoTotal}}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>Cantidad abonada:</p>
                    <p>${{servicio.partePago}}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>Monto restante a pagar:</p>
                    <p>${{servicio.aPagar}}</p>
                </div>
            </div>
        </div>
        <div class="text-center mt-4">
            <a href="{% url 'servicios:formCodigo' %}" class="myButton">Atrás</a>
        </div>
    </div> <!-- Cierre del div que crea la tarjeta -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>